package com.rtfs.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.rtfs.greendao.JokeCache;
import com.rtfs.greendao.NewsCache;
import com.rtfs.greendao.PictureCache;
import com.rtfs.greendao.GirlCache;
import com.rtfs.greendao.VideoCache;

import com.rtfs.greendao.JokeCacheDao;
import com.rtfs.greendao.NewsCacheDao;
import com.rtfs.greendao.PictureCacheDao;
import com.rtfs.greendao.GirlCacheDao;
import com.rtfs.greendao.VideoCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig jokeCacheDaoConfig;
    private final DaoConfig newsCacheDaoConfig;
    private final DaoConfig pictureCacheDaoConfig;
    private final DaoConfig girlCacheDaoConfig;
    private final DaoConfig videoCacheDaoConfig;

    private final JokeCacheDao jokeCacheDao;
    private final NewsCacheDao newsCacheDao;
    private final PictureCacheDao pictureCacheDao;
    private final GirlCacheDao girlCacheDao;
    private final VideoCacheDao videoCacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jokeCacheDaoConfig = daoConfigMap.get(JokeCacheDao.class).clone();
        jokeCacheDaoConfig.initIdentityScope(type);

        newsCacheDaoConfig = daoConfigMap.get(NewsCacheDao.class).clone();
        newsCacheDaoConfig.initIdentityScope(type);

        pictureCacheDaoConfig = daoConfigMap.get(PictureCacheDao.class).clone();
        pictureCacheDaoConfig.initIdentityScope(type);

        girlCacheDaoConfig = daoConfigMap.get(GirlCacheDao.class).clone();
        girlCacheDaoConfig.initIdentityScope(type);

        videoCacheDaoConfig = daoConfigMap.get(VideoCacheDao.class).clone();
        videoCacheDaoConfig.initIdentityScope(type);

        jokeCacheDao = new JokeCacheDao(jokeCacheDaoConfig, this);
        newsCacheDao = new NewsCacheDao(newsCacheDaoConfig, this);
        pictureCacheDao = new PictureCacheDao(pictureCacheDaoConfig, this);
        girlCacheDao = new GirlCacheDao(girlCacheDaoConfig, this);
        videoCacheDao = new VideoCacheDao(videoCacheDaoConfig, this);

        registerDao(JokeCache.class, jokeCacheDao);
        registerDao(NewsCache.class, newsCacheDao);
        registerDao(PictureCache.class, pictureCacheDao);
        registerDao(GirlCache.class, girlCacheDao);
        registerDao(VideoCache.class, videoCacheDao);
    }
    
    public void clear() {
        jokeCacheDaoConfig.getIdentityScope().clear();
        newsCacheDaoConfig.getIdentityScope().clear();
        pictureCacheDaoConfig.getIdentityScope().clear();
        girlCacheDaoConfig.getIdentityScope().clear();
        videoCacheDaoConfig.getIdentityScope().clear();
    }

    public JokeCacheDao getJokeCacheDao() {
        return jokeCacheDao;
    }

    public NewsCacheDao getNewsCacheDao() {
        return newsCacheDao;
    }

    public PictureCacheDao getPictureCacheDao() {
        return pictureCacheDao;
    }

    public GirlCacheDao getGirlCacheDao() {
        return girlCacheDao;
    }

    public VideoCacheDao getVideoCacheDao() {
        return videoCacheDao;
    }

}
